### ISSUE TITLE
Trash script

### ISSUE THREAD

**Issue by RegularID** [joeengo/engospy#2]
Complete ass script, also your shitty onClientEvent method is detected LOL!
Learn to script retard.

😘 
-PonyID

**Comment by f6oor** [comment]
This guy is so hot

**Comment by joeengo** [comment]
> Complete ass script, also your shitty onClientEvent method is detected LOL! Learn to script retard.
> 
> 😘 -PonyID
You could of atleast gave me some info on how its detected, instead of completely shitting on people who can't code on the level you expect.

**Comment by RegularID** [comment]
> > Complete ass script, also your shitty onClientEvent method is detected LOL! Learn to script retard.
> > 😘 -PonyID
> 
> You could of atleast gave me some info on how its detected, instead of completely shitting on people who can't code on the level you expect.

Ask XAXA or he might not know but fuck you I won't help you

**Comment by f6oor** [comment]
Dude the code is so shit just delete the repo no one even uses it XD

**Comment by joeengo** [comment]
> Dude the code is so shit just delete the repo no one even uses it XD

you have nothing better todo then come here and tell me that, really?
